
CREATE ROLE sparkuser WITH LOGIN PASSWORD 'sparkuser';


GRANT CONNECT ON DATABASE arb TO sparkuser;
GRANT USAGE ON SCHEMA public TO sparkuser;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sparkuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sparkuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO sparkuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO sparkuser;
